from __future__ import annotations

import os
from pathlib import Path

import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
PACKAGE = ROOT / "reports" / "submission_package"
MAIN_FIGS = PACKAGE / "main_figures"
SUPP_FIGS = PACKAGE / "supplementary_figures"
MAIN_TABLES = PACKAGE / "main_tables"
SUPP_TABLES = PACKAGE / "supplementary_tables"
OUT = DOCS / "manuscript_draft_full_zh_integrated_20260531.md"


def rel(path: Path) -> str:
    return Path(os.path.relpath(path.resolve(), DOCS.resolve())).as_posix()


def clean_value(value: object) -> str:
    if pd.isna(value):
        return ""
    text = str(value)
    text = text.replace("\n", " ").replace("\r", " ")
    text = text.replace("|", "\\|")
    return text


def table_markdown(path: Path) -> str:
    frame = pd.read_csv(path)
    frame = frame.fillna("")
    headers = [clean_value(col) for col in frame.columns]
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join(["---"] * len(headers)) + " |",
    ]
    for _, row in frame.iterrows():
        lines.append("| " + " | ".join(clean_value(row[col]) for col in frame.columns) + " |")
    return "\n".join(lines)


def figure(path: Path, caption: str) -> str:
    return f"![{caption}]({rel(path)})\n\n**{caption}**"


def table_block(label: str, caption: str, path: Path) -> str:
    return "\n".join(
        [
            f"**{label}. {caption}**",
            "",
            table_markdown(path),
            "",
            f"数据文件：`{rel(path)}`",
        ]
    )


def main() -> None:
    lines: list[str] = [
        "# FZYC-Mol：面向结构分布偏移的验证集选择与适用域感知多专家分子性质预测框架",
        "",
        "完整中文整合初稿：2026-05-31",
        "",
        "> 说明：本文为计算分子 AI / 化学信息学 / 药物发现机器学习论文初稿，不包含湿实验。所有结果来自公开分子性质数据集、官方划分协议、结构外推评估、活性悬崖评估、校准/不确定性/适用域分析、可解释性分析和外部 ADMET appendix benchmark。",
        "",
        "## 摘要",
        "",
        "分子性质预测是药物发现、ADMET 评估、毒性筛选和先导化合物优化中的核心计算任务。近年来，图神经网络、定向消息传递神经网络、分子指纹、描述符模型和分子预训练编码器在多个公开基准上取得了进展。然而，现有研究仍存在三个可靠性缺口：第一，随机划分或单一 scaffold 划分可能高估模型对结构新颖分子的泛化能力；第二，不同分子端点对表示类型和模型家族的偏好明显不同，单一架构很难稳定覆盖溶解度、脂溶性、渗透性、酶抑制、血脑屏障和毒性等任务；第三，许多 benchmark 主要报告点预测性能，而对不确定性、校准、适用域、活性悬崖、早期富集和化学可解释性的系统证据不足。",
        "",
        "本文提出 FZYC-Mol，一个严格基于验证集选择且具备适用域感知能力的多专家分子性质预测框架。FZYC-Mol 整合图神经网络、D-MPNN/Chemprop、随机森林、XGBoost、LightGBM、ExtraTrees、多类型分子指纹、RDKit 描述符模型、BRICS/Murcko/官能团 motif 专家、ChemBERTa 与 MoLFormer 冻结 embedding、validation stacking、adaptive consensus、不确定性模型和适用域加权机制。所有最终预测策略均只使用 validation split 进行选择，test split 仅用于最终报告，从而避免测试集策略选择泄漏。",
        "",
        "在 MoleculeNet 上，FZYC-Mol 表现出端点特异性的竞争性能：ESOL 达到 RMSE 0.5829 +/- 0.0352，BACE 达到 ROC-AUC 0.8753 +/- 0.0230，ClinTox 达到 ROC-AUC 0.9489 +/- 0.0302。进一步地，基于 validation-only 原则的 rescue-integrated selector 在 Lipo 上将 RMSE 从 0.7078 +/- 0.0389 降低到 0.6835 +/- 0.0439。TDC ADMET 结果显示，validation selector 在 HIA_Hou、Pgp_Broccatelli 和 BBB_Martins 上分别达到 ROC-AUC 0.9792、0.9357 和 0.9182。结构分布偏移实验显示，随机划分性能可能显著高估实际泛化能力，例如 ESOL RMSE 从 random split 的 0.6000 上升到 scaffold split 的 0.6868，并在 structure-separated split 中进一步上升到 0.7560；BACE ROC-AUC 从 0.8890 降至 0.8766 和 0.7853；TDC HIA_Hou ROC-AUC 从 0.9945 降至 0.8901 和 0.8253。",
        "",
        "除主性能指标外，本文还报告 Brier score、expected calibration error、EF1%、EF5%、BEDROC20、top-k recall、split-conformal coverage、risk-coverage 行为、ensemble variance、scaffold distance、Tanimoto 适用域分数、validation-trained error model 和 reconstruction-based unfamiliarity score。重构陌生度提供了与传统 Tanimoto 相似性互补的适用域信号，hybrid reconstruction-plus-AD score 与绝对误差的平均 Spearman 相关达到 0.2225。Motif attribution 进一步在 BBBP、BACE 和 ClinTox 上提供化学可解释信号。总体而言，FZYC-Mol 将分子性质预测从单一 benchmark 分数比较推进到结构分布偏移下的验证集控制、可靠性评估和化学解释闭环。",
        "",
        "## 关键词",
        "",
        "分子性质预测；ADMET；适用域；不确定性估计；validation stacking；结构分布偏移；活性悬崖；分子指纹；Chemprop；分子预训练模型",
        "",
        "## 图文摘要",
        "",
        figure(MAIN_FIGS / "Figure_1_FZYC_Mol_framework.png", "图 1. FZYC-Mol 框架总览。分子输入被转化为图、指纹、描述符、motif 和冻结预训练 embedding 等多视图表示，并进入异质专家池。最终预测策略只由验证集选择，输出包括性质预测、风险信号、适用域判断和 motif 解释。"),
        "",
        "# 1. 引言",
        "",
        "分子性质预测是现代计算药物发现的基础任务。给定一个分子结构，模型可以在实验测量之前估计溶解度、脂溶性、膜渗透性、血脑屏障穿透、酶抑制、毒性或其他 ADMET 相关性质。这类模型能够降低实验成本、提高虚拟筛选效率、支持 hit-to-lead 优化，并帮助研究者尽早识别高风险化合物。",
        "",
        "分子机器学习已经从手工描述符和传统机器学习快速发展到图神经网络、消息传递神经网络和分子预训练模型。Morgan 指纹、MACCS keys、atom-pair 和 torsion fingerprints 结合随机森林、ExtraTrees、XGBoost 或 LightGBM，仍然在许多小中型分子数据集上非常强。D-MPNN 和 Chemprop 通过分子图直接学习原子-键相互作用，是药物发现任务中的常用强基线。ChemBERTa、MoLFormer、Uni-Mol 等分子 foundation model 则尝试从大规模未标注分子语料中学习可迁移表示。",
        "",
        "然而，分子性质预测的核心挑战不仅是平均性能，更是可靠性。在真实药物发现中，测试化合物常常来自新的 scaffold、新的化学系列或低相似度区域。随机划分可能让训练集和测试集共享高度相似结构，从而高估泛化能力。与此同时，不同端点的结构-性质关系差异明显，单一模型家族很难在所有端点上稳定最优。实际应用还要求模型给出不确定性、校准情况、适用域状态、活性悬崖风险和可解释化学线索。",
        "",
        "因此，本文提出 FZYC-Mol：一个验证集选择、适用域感知、多专家融合的分子性质预测框架。本文的核心不是声称某个单一架构普遍优于所有模型，而是构建一个可复现的分子 AI 可靠性评估闭环：在不使用测试集选择策略的前提下，整合多类专家，进行结构分布偏移评估，并系统报告可靠性和解释性证据。",
        "",
        "本文主要贡献如下：",
        "",
        "1. 提出严格 validation-only 的分子专家选择协议，避免测试集策略选择泄漏。",
        "2. 构建整合图模型、Chemprop、指纹、描述符、motif 专家和冻结预训练编码器的多专家框架。",
        "3. 在 MoleculeNet、TDC ADMET、官方 PyTDC split、MoleculeACE、低相似度 hard subset 和 structure-separated split 上进行广泛评估。",
        "4. 引入不确定性、校准、适用域、conformal prediction、validation-trained error model 和 reconstruction-based unfamiliarity 等可靠性模块。",
        "5. 通过 BRICS fragment、Murcko scaffold 和官能团 motif attribution 加强化学解释。",
        "6. 对低分模块进行 targeted rescue，并通过完整 validation-only selector integration 验证是否应纳入主结果。",
        "",
        "# 2. 相关工作",
        "",
        "## 2.1 分子性质预测基准",
        "",
        "MoleculeNet 是分子机器学习中最常用的公开基准之一，覆盖物理化学、生物物理、生理学和毒性等任务。本文使用 ESOL、FreeSolv、Lipo、BBBP、BACE 和 ClinTox 作为核心 MoleculeNet endpoint。Therapeutics Data Commons 提供了面向药物研发任务的数据和 benchmark，本文使用 Caco2_Wang、HIA_Hou、Pgp_Broccatelli、Bioavailability_Ma、BBB_Martins、CYP2C9_Veith、CYP2D6_Veith 和 CYP3A4_Veith 作为 TDC ADMET 迁移评估，并进一步扩展到 22 个 PyTDC ADMET/Tox endpoint 的 full-panel appendix benchmark。",
        "",
        "## 2.2 图模型、Chemprop 与传统指纹模型",
        "",
        "图神经网络将分子视为原子和键构成的图结构，通过消息传递学习局部结构表示。D-MPNN/Chemprop 是分子性质预测中的强神经基线。另一方面，Morgan 指纹、RDKit 描述符和树模型仍然具有很强竞争力，尤其在小样本和结构分布偏移条件下。本文将这些模型均作为候选专家，而不是预设某一模型家族必然最优。",
        "",
        "## 2.3 分子预训练编码器与低成本 rescue heads",
        "",
        "分子预训练编码器能够从大规模分子语料中学习通用表示，但近期 benchmark 显示，大模型或预训练模型并不自动在所有 drug-discovery endpoint 上胜出。本文评估 ChemBERTa 和 MoLFormer frozen embeddings，并进一步加入 nonlinear rescue heads：保持 embedding 冻结，将其与 RDKit descriptors 拼接，再训练 ExtraTrees 或 LightGBM。该策略用于补强 frozen pretrained linear heads 这一低分模块，但是否进入最终预测仍由 validation-only selector 决定。",
        "",
        "## 2.4 适用域、校准、活性悬崖和可解释性",
        "",
        "实际药物发现需要判断预测是否处于模型适用域内。常见信号包括 Tanimoto similarity、scaffold distance、ensemble variance、density 或 error model。本文进一步引入 reconstruction-based unfamiliarity，用于判断测试分子是否难以被训练分布的 Morgan+descriptor 特征流形重构。活性悬崖和早期富集指标则补充 ROC-AUC/RMSE 的不足，帮助评估模型是否能将真正有价值的候选分子排在前列。",
        "",
        "# 3. 方法",
        "",
        "## 3.1 问题定义",
        "",
        "给定分子数据集 D = {(x_i, y_i)}，其中 x_i 为 SMILES 或分子图，y_i 为连续性质或二分类标签。传统方法训练单一专家 f_m(x)。FZYC-Mol 考虑 M 个专家：f_1, f_2, ..., f_M，并学习一个组合策略 g(f_1(x), ..., f_M(x))。g 可以是最佳验证专家、固定 consensus、validation stacking、adaptive consensus 或适用域加权 consensus。关键约束是：g 只由 validation split 选择，test split 不参与策略选择。",
        "",
        "## 3.2 数据集和划分",
        "",
        table_block("表 1", "数据集与评估协议。表中列出 MoleculeNet 与 TDC ADMET endpoint、任务类型、样本量、主指标、划分方式和特殊评估模块。", MAIN_TABLES / "Table_1_Dataset_protocol.csv"),
        "",
        "## 3.3 专家池与候选策略",
        "",
        "FZYC-Mol 包含以下专家家族：传统 Morgan 指纹模型、多指纹树模型、GIN/D-MPNN/FZYC graph 模型、Chemprop D-MPNN 与 Chemprop-RDKit、冻结 ChemBERTa/MoLFormer embedding heads、descriptor MLP、BRICS/Murcko/functional-group motif experts，以及不确定性和适用域加权模块。候选策略包括 best validation expert、fixed consensus、ridge/logistic stacking、adaptive consensus 和 hybrid uncertainty/AD consensus。",
        "",
        "在定位到 frozen pretrained linear heads 表现较弱后，本文新增 pretrained rescue heads：保持 ChemBERTa/MoLFormer embedding 冻结，将其与 RDKit descriptors 拼接，并训练 ExtraTrees/LightGBM。随后将 rescue-aware candidates 接回完整 validation-only selector pool，只有验证集支持时才采用。",
        "",
        "## 3.4 可靠性与可解释性模块",
        "",
        "可靠性模块包括 ensemble standard deviation、classification confidence、max-train Morgan Tanimoto similarity、inverse Tanimoto distance、scaffold distance、validation-trained error model、hybrid error-plus-AD score、reconstruction-based unfamiliarity 和 hybrid reconstruction-plus-AD score。可解释性模块包括 BRICS fragment、Murcko scaffold、官能团 motif attribution、fragment enrichment 和 scaffold-level boundary case 分析。",
        "",
        "## 3.5 评价指标",
        "",
        "回归任务使用 RMSE、MAE、R2、Spearman、Pearson 和 conformal interval width。分类任务使用 ROC-AUC、PR-AUC、accuracy、F1、Brier score、ECE、EF1%、EF5%、BEDROC20、top-k recall 和 conformal prediction set coverage。可靠性指标包括 uncertainty/OOD score 与绝对误差的 Spearman 相关、risk-coverage AUC 和 top-10% high-error enrichment。",
        "",
        "# 4. 实验设置",
        "",
        "所有实验均为公开数据集上的计算实验，不包含湿实验。RDKit 用于分子解析、描述符、指纹、scaffold 和官能团识别。传统模型基于 scikit-learn、XGBoost 和 LightGBM；神经模型使用 PyTorch 相关实现；Chemprop baseline 使用官方 Chemprop workflow；TDC 数据和官方 split 通过 PyTDC 获取。主要 MoleculeNet 实验使用五个 scaffold split seeds，TDC full-panel appendix 使用官方 scaffold split 和三种 seeds。",
        "",
        "# 5. 结果",
        "",
        "## 5.1 MoleculeNet 主性能",
        "",
        table_block("表 2", "MoleculeNet 主结果。该表同时保留原 FZYC-Mol validation selector 和 conservative targeted rescue selector；后者仅在 Lipo 上通过 validation-only integration 采用 rescue-aware candidate。", MAIN_TABLES / "Table_2_MoleculeNet_main_results.csv"),
        "",
        figure(MAIN_FIGS / "Figure_2_MoleculeNet_model_family_ranks.png", "图 2. MoleculeNet endpoint 内模型家族 rank heatmap。Rank 1 表示该 endpoint 内最优。图中显示不同 endpoint 的最优模型家族不同，targeted rescue selector 只在 Lipo 上形成主性能改进。"),
        "",
        figure(MAIN_FIGS / "Figure_3_MoleculeNet_main_performance.png", "图 3. MoleculeNet 主性能散点图。回归任务为 RMSE，分类任务为 ROC-AUC。FZYC-Mol validation selector 在 ESOL、BACE、ClinTox 上保持最优或近最优，targeted rescue selector 在 Lipo 上取得最优 RMSE。"),
        "",
        "Table 2 和 Figure 2/3 共同说明，分子 endpoint 之间存在明显模型偏好差异。ESOL、BACE 和 ClinTox 由 validation selector 表现最佳；FreeSolv 中 Chemprop-RDKit 仍然最强；BBBP 中 multi-fingerprint ExtraTrees 最强；Lipo 则由 rescue-integrated targeted selector 将 RMSE 降至 0.6835 +/- 0.0439。该结果支持本文的核心观点：多专家框架的价值在于端点自适应和验证集控制，而不是强行使用单一模型家族。",
        "",
        "## 5.2 TDC ADMET 迁移与官方 split",
        "",
        table_block("表 3", "TDC ADMET 迁移与官方 PyTDC random/scaffold split 结果。该表展示 validation selector 与 LGBM/RF Morgan+RDKit official split baseline。", MAIN_TABLES / "Table_3_TDC_ADMET_official_splits.csv"),
        "",
        figure(MAIN_FIGS / "Figure_5_Official_TDC_ADMET_scaffold_delta.png", "图 5. 官方 PyTDC random-to-scaffold 性能变化。正值表示 scaffold split 更难，显示 ADMET endpoint 对划分方式高度敏感。"),
        "",
        "TDC ADMET 结果显示，validation selector 在 HIA_Hou、Pgp_Broccatelli 和 BBB_Martins 上分别达到 ROC-AUC 0.9792、0.9357 和 0.9182。官方 split baseline 进一步显示 random split 到 scaffold split 的性能变化依赖 endpoint 和模型家族，强调 ADMET 评估中官方和结构感知划分的重要性。",
        "",
        "## 5.3 Split-realism 与结构分布偏移",
        "",
        table_block("表 4", "随机划分、scaffold 划分和 structure-separated 划分下的 split-realism 结果。", MAIN_TABLES / "Table_4_Split_realism.csv"),
        "",
        figure(MAIN_FIGS / "Figure_4_Split_realism_structure_shift.png", "图 4. 结构分布偏移下的 split-realism 曲线。多个 endpoint 在 structure-separated split 下显著退化，说明随机划分可能高估真实泛化能力。"),
        "",
        "Split-realism 结果显示，ESOL、BACE、TDC HIA_Hou、Bioavailability_Ma 和 Pgp_Broccatelli 等 endpoint 在结构更严格的划分下表现明显下降。并非每个数据集都严格单调退化，但总体结论非常清楚：分子预测论文不能只依赖 random split 报告性能。",
        "",
        "## 5.4 不确定性、校准、适用域和 reconstruction unfamiliarity",
        "",
        table_block("表 6", "可靠性和适用域分析。表中比较 reconstruction unfamiliarity、inverse Tanimoto、hybrid AD score、conformal coverage 等信号。", MAIN_TABLES / "Table_6_Reliability_AD.csv"),
        "",
        figure(MAIN_FIGS / "Figure_6_Uncertainty_AD_reliability.png", "图 6. 高风险分子预测的可靠性信号。Reconstruction-based unfamiliarity 与 hybrid AD signal 为识别高误差样本提供互补信息。"),
        "",
        "重构陌生度与绝对误差的平均 Spearman 相关为 0.2032，top-10% high-error enrichment 为 2.0767；hybrid reconstruction-plus-AD score 的平均 Spearman 相关达到 0.2225。该结果说明，基于训练分布特征流形的 reconstruction error 可以作为传统相似性适用域指标的补充。",
        "",
        "## 5.5 活性悬崖、早期富集与 motif 解释",
        "",
        figure(MAIN_FIGS / "Figure_7_Motif_fragment_interpretation.png", "图 7. Motif attribution 与 fragment-level 化学解释。图中展示 BRICS、Murcko scaffold 和官能团 motif 对代表性分类 endpoint 的贡献。"),
        "",
        "Motif experts 在 BBBP、BACE 和 ClinTox 上分别达到 ROC-AUC 0.9133、0.8281 和 0.8592。BBBP 中极性片段、羟基、羧酸盐、内酰胺和芳香羟基等 motif 与血脑屏障穿透表现出合理关联；BACE 中卤素、芳基甲基、醚和疏水芳香片段较突出；ClinTox 中季铵、苯胺、芳香氮、羰基和稠环结构值得关注。这些解释应被视为关联证据，而非因果机制证明。",
        "",
        "补充图 S7 进一步展示 enrichment 与 activity-cliff 相关结果：",
        "",
        figure(SUPP_FIGS / "Figure_S7_Enrichment_activity_cliffs.png", "图 S7. 早期富集和活性悬崖诊断。EF1%、EF5%、BEDROC20 和 top-k recall 补充 ROC-AUC，以评估虚拟筛选排序能力。"),
        "",
        "## 5.6 Ablation、显著性与 selector 行为",
        "",
        table_block("表 5", "Ablation 与统计证据。表中汇总 family ablation、win/tie/loss 和 paired test 结果。", MAIN_TABLES / "Table_5_Ablation_significance.csv"),
        "",
        figure(SUPP_FIGS / "Figure_S3_Ablation_significance.png", "图 S3. Ablation 与显著性分析。单一 expert family 通常弱于完整 validation selector，但并非每个新增专家都会单调改善每个 endpoint。"),
        "",
        figure(SUPP_FIGS / "Figure_S4_Validation_selector_map.png", "图 S4. Validation selector 选择图谱。不同 endpoint 选择不同候选策略，支持 endpoint-specific expert routing。"),
        "",
        "Ablation 结果显示，chemprop_only、pretrained_only 和 core_only 均不能稳定覆盖所有 endpoint。与此同时，移除某些专家在个别 endpoint 上可能略有改善，说明候选池扩张本身并不必然带来性能提升，selector 需要稳定性约束和端点级判断。",
        "",
        "## 5.7 Conformal prediction、risk coverage 与校准",
        "",
        figure(SUPP_FIGS / "Figure_S1_Risk_coverage_curves.png", "图 S1. Risk-coverage curves。低风险 retained subset 通常具有更低误差或更高分类性能，说明风险排序可用于筛选可靠预测。"),
        "",
        figure(SUPP_FIGS / "Figure_S2_Calibration_curves.png", "图 S2. 分类校准曲线。校准和 Brier score 应与 ROC-AUC 一起报告，尤其在 ClinTox 等小样本不平衡任务上。"),
        "",
        figure(SUPP_FIGS / "Figure_S5_Conformal_diagnostics.png", "图 S5. Conformal prediction 诊断。该图展示 coverage、set size 或 interval width，用于评估不确定性区间是否满足预期覆盖。"),
        "",
        table_block("表 S6", "Reliability summary。该表汇总校准、适用域、risk coverage、conformal prediction 等可靠性结果。", SUPP_TABLES / "Table_S6_Reliability_summary.csv"),
        "",
        "## 5.8 效率与实用性",
        "",
        table_block("表 7", "计算效率。表中报告模型家族、硬件类别、拟合时间、预测时间和 metric row 数。", MAIN_TABLES / "Table_7_Efficiency.csv"),
        "",
        figure(SUPP_FIGS / "Figure_S6_Efficiency_tradeoff.png", "图 S6. 性能与计算效率权衡。多个强 baseline 可在 CPU 上快速训练和预测，适合早期筛选和快速迭代。"),
        "",
        "效率结果支持 practical molecular AI 的叙事。框架并不要求每个 endpoint 都由大型神经网络解决，强传统模型与可靠性诊断结合即可形成较低成本的实验闭环。",
        "",
        "## 5.9 外部 ADMET appendix 与 roughness 分析",
        "",
        table_block("表 S8", "OpenADMET-ExpansionRx fast external appendix benchmark。", SUPP_TABLES / "Table_S8_OpenADMET_ExpansionRx_fast_external.csv"),
        "",
        table_block("表 S9", "PyTDC full-panel ADMET/Tox fast appendix benchmark。该表覆盖 22/22 endpoint。", SUPP_TABLES / "Table_S9_TDC_full_panel_fast_appendix.csv"),
        "",
        table_block("表 S10", "TDC performance-mode retained-best appendix。加入 Top-K/stacking、XGBoost、CatBoost、target transform、robust loss 和 undersampling ensemble，并按 endpoint 保留更好结果。", SUPP_TABLES / "Table_S10_TDC_performance_mode_retained_best.csv"),
        "",
        table_block("表 S11", "TDC roughness and literature-alignment appendix。通过最近邻相似分子标签不一致或 normalized target jump 解释困难 endpoint。", SUPP_TABLES / "Table_S11_TDC_roughness_literature_alignment.csv"),
        "",
        "TDC performance-mode retained-best appendix 相比 full-panel fast appendix 改善了五个 endpoint：half_life_obach、vdss_lombardo、ppbr_az、clearance_microsome_az 和 clearance_hepatocyte_az。Roughness 诊断显示，高 local roughness 的 ADME regression endpoint 也是性能模式补强更容易奏效的 endpoint，说明 tabular experts、target transform 和 validation-only ensembles 对局部不连续结构-性质关系特别有价值。",
        "",
        "## 5.10 低分模型模块补强与 rescue-integrated selector",
        "",
        table_block("表 S12", "MoleculeNet meta-pool selector diagnostic。该表显示简单合并现有候选池并不能改善主 selector。", SUPP_TABLES / "Table_S12_MoleculeNet_meta_pool_selector.csv"),
        "",
        table_block("表 S13", "Pretrained rescue heads。该表比较 nonlinear rescue heads 与 best frozen-linear pretrained heads。", SUPP_TABLES / "Table_S13_Pretrained_rescue_heads.csv"),
        "",
        table_block("表 S14", "MoleculeNet rescue-integrated selector。该表将 rescue heads 接回完整 validation-only selector pool，最终只有 Lipo 选择 rescue-aware candidate。", SUPP_TABLES / "Table_S14_MoleculeNet_rescue_integrated_selector.csv"),
        "",
        "低分模块分析显示，frozen pretrained linear heads 是当前最弱的 standalone family。通过将 ChemBERTa/MoLFormer embedding 与 RDKit descriptors 拼接，并训练 ExtraTrees/LightGBM rescue heads，Table S13 显示该模块在 5/6 个 MoleculeNet endpoint 上超过原 best frozen-linear pretrained head。然而，真正决定主文是否采用的是 Table S14 的 full selector integration：只有 Lipo 被 validation-only selector 接纳 rescue-aware candidate，RMSE 从 0.7078 降至 0.6835；其他 endpoint 保留原 selector。这一结果避免了过度宣称，也强化了 validation-only 原则。",
        "",
        "# 6. 讨论",
        "",
        "## 6.1 端点特异性是分子性质预测的核心事实",
        "",
        "本文结果显示，不同 endpoint 的最优模型家族并不一致。Chemprop-RDKit 在 FreeSolv 上最强，multi-fingerprint ExtraTrees 在 BBBP 上最强，validation selector 在 ESOL、BACE 和 ClinTox 上最强，targeted rescue selector 在 Lipo 上最强。TDC ADMET 任务中，多指纹和 tabular experts 经常具有很强竞争力。这说明分子 AI 框架应强调 endpoint-specific expert selection，而不是单一架构的普适最优。",
        "",
        "## 6.2 大模型和复杂模型并不自动获胜",
        "",
        "Graph Transformer probes 和 frozen pretrained encoders 并未稳定超过强传统 baseline。Rescue-head 实验说明，弱的 pretrained module 可以通过轻量 nonlinear tabular heads 被修复，但 full validation-only integration 只在 Lipo 上接受该补强。因此，本文更稳妥的结论是：模型复杂度本身不是胜利条件，验证集控制和端点级选择才是关键。",
        "",
        "## 6.3 结构划分应成为分子 benchmark 的常规轴",
        "",
        "Random split 往往高估真实泛化能力。Scaffold 和 structure-separated split 更接近 scaffold hopping、新化学系列和未探索化学空间中的实际应用场景。本文的 split-realism 结果显示，结构分布偏移会显著改变模型结论，因此单一随机划分报告不足以支持可靠药物发现声明。",
        "",
        "## 6.4 可靠性不等于平均准确率",
        "",
        "一个模型即使具有较高 ROC-AUC 或较低 RMSE，也可能在适用域外、活性悬崖区域或低相似度区域表现不可靠。FZYC-Mol 将 uncertainty、AD、reconstruction unfamiliarity、conformal coverage、calibration 和 enrichment 共同纳入报告，使模型输出从点估计扩展为可风险分层的预测证据。",
        "",
        "## 6.5 化学解释增强框架可信度",
        "",
        "Motif attribution 和 fragment enrichment 将模型行为连接到可识别的化学结构单元。虽然这些解释不能直接证明因果机制，但可以帮助审稿人和药物化学用户理解模型为何在某些 endpoint 上给出特定预测，也能辅助识别潜在的高风险结构模式。",
        "",
        "# 7. 局限性",
        "",
        "1. 本研究不包含湿实验验证，所有结论均来自公开数据集上的计算评估。",
        "2. Exact Polaris benchmark 未在本轮纳入，尽管官方 PyTDC ADMET split 和外部 ADMET appendix 已补强。",
        "3. TDC structure-separated stress test 的 seed 数少于主 MoleculeNet 实验。",
        "4. ChemBERTa 和 MoLFormer 主要以 frozen encoder 形式使用，full fine-tuning 可能改善部分 endpoint，但也会增加计算成本和过拟合风险。",
        "5. ClinTox 等小样本不平衡数据集存在 seed-level instability，ROC-AUC 应与 PR-AUC、Brier、ECE 和 conformal diagnostics 一起解释。",
        "6. Motif attribution 和 fragment enrichment 是关联解释，不能被解读为因果机制证明。",
        "",
        "# 8. 结论",
        "",
        "本文提出 FZYC-Mol，一个验证集选择、适用域感知、多专家分子性质预测框架。FZYC-Mol 不依赖单一模型家族，而是整合图模型、Chemprop、分子指纹、描述符模型、motif experts、冻结预训练编码器、validation stacking、adaptive consensus、不确定性建模和适用域加权。所有最终策略选择均只使用 validation split，test split 保留用于最终评估。",
        "",
        "跨 MoleculeNet、TDC ADMET、官方 PyTDC split、MoleculeACE、低相似度 hard subset 和 structure-separated split 的结果表明，FZYC-Mol 能够提供比单一 leaderboard score 更完整的可靠性证据。主表显示，框架在 ESOL、BACE、ClinTox 和 Lipo 等 endpoint 上通过不同 validation-accepted 策略取得强结果；外部 ADMET appendix 和 roughness 诊断进一步说明，强 tabular experts、target transform 和 validation-only ensemble 对困难 ADME regression endpoint 具有实际价值；rescue-integrated selector 则展示了如何在不破坏 validation-only 原则的前提下补强低分模块。",
        "",
        "因此，FZYC-Mol 的核心贡献不是声称某个架构普遍胜出，而是提供一个可复现的可靠性框架：验证集控制的模型选择、异质专家池、结构分布偏移评估、不确定性与适用域诊断、活性悬崖与富集分析、motif-level 解释和 practical efficiency reporting。",
        "",
        "# 9. 图表对应关系总览",
        "",
        "| 章节 | 图/表 | 文件 | 对应内容 |",
        "| --- | --- | --- | --- |",
        "| 图文摘要 | 图 1 | `reports/submission_package/main_figures/Figure_1_FZYC_Mol_framework.png` | 框架总览 |",
        "| 方法 | 表 1 | `reports/submission_package/main_tables/Table_1_Dataset_protocol.csv` | 数据集与协议 |",
        "| 结果 5.1 | 表 2 | `reports/submission_package/main_tables/Table_2_MoleculeNet_main_results.csv` | MoleculeNet 主结果 |",
        "| 结果 5.1 | 图 2 | `reports/submission_package/main_figures/Figure_2_MoleculeNet_model_family_ranks.png` | MoleculeNet rank heatmap |",
        "| 结果 5.1 | 图 3 | `reports/submission_package/main_figures/Figure_3_MoleculeNet_main_performance.png` | MoleculeNet 性能散点 |",
        "| 结果 5.2 | 表 3 | `reports/submission_package/main_tables/Table_3_TDC_ADMET_official_splits.csv` | TDC ADMET 官方 split |",
        "| 结果 5.2 | 图 5 | `reports/submission_package/main_figures/Figure_5_Official_TDC_ADMET_scaffold_delta.png` | 官方 random-to-scaffold delta |",
        "| 结果 5.3 | 表 4 | `reports/submission_package/main_tables/Table_4_Split_realism.csv` | split realism |",
        "| 结果 5.3 | 图 4 | `reports/submission_package/main_figures/Figure_4_Split_realism_structure_shift.png` | 结构分布偏移曲线 |",
        "| 结果 5.4 | 表 6 | `reports/submission_package/main_tables/Table_6_Reliability_AD.csv` | 可靠性与适用域 |",
        "| 结果 5.4 | 图 6 | `reports/submission_package/main_figures/Figure_6_Uncertainty_AD_reliability.png` | 可靠性信号 |",
        "| 结果 5.5 | 图 7 | `reports/submission_package/main_figures/Figure_7_Motif_fragment_interpretation.png` | motif 解释 |",
        "| 结果 5.6 | 表 5 | `reports/submission_package/main_tables/Table_5_Ablation_significance.csv` | ablation 与统计证据 |",
        "| 结果 5.8 | 表 7 | `reports/submission_package/main_tables/Table_7_Efficiency.csv` | 效率 |",
        "| 结果 5.9 | 表 S8-S11 | `reports/submission_package/supplementary_tables/` | 外部 ADMET、TDC full-panel、performance-mode、roughness |",
        "| 结果 5.10 | 表 S12-S14 | `reports/submission_package/supplementary_tables/` | meta-pool、pretrained rescue、rescue-integrated selector |",
        "",
        "# 10. 参考文献草稿",
        "",
        "1. Wu Z, Ramsundar B, Feinberg EN, et al. MoleculeNet: a benchmark for molecular machine learning. Chemical Science, 2018.",
        "2. Huang K, Fu T, Gao W, et al. Therapeutics Data Commons: machine learning datasets and tasks for drug discovery and development. NeurIPS Datasets and Benchmarks, 2021.",
        "3. Yang K, Swanson K, Jin W, et al. Analyzing learned molecular representations for property prediction. Journal of Chemical Information and Modeling, 2019.",
        "4. Rogers D, Hahn M. Extended-connectivity fingerprints. Journal of Chemical Information and Modeling, 2010.",
        "5. Landrum G. RDKit: open-source cheminformatics software.",
        "6. Chithrananda S, Grand G, Ramsundar B. ChemBERTa: large-scale self-supervised pretraining for molecular property prediction.",
        "7. Ross J, Belgodere B, Chenthamarakshan V, et al. Large-scale chemical language representations capture molecular structure and properties. MoLFormer.",
        "8. van Tilborg D, Alenicheva A, Grisoni F. Exposing the limitations of molecular machine learning with activity cliffs. MoleculeACE.",
        "9. Therapeutics Data Commons and PyTDC benchmark documentation.",
        "10. Recent ADMET reliability, OOD, tabular foundation model, and molecular foundation model benchmark papers discussed in `docs/recent_literature_competitive_improvement_20260531.md`.",
    ]

    OUT.write_text("\n\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
